{% set name = "typst-py" %}
{% set pypi_name = "typst" %}
{% set version = "0.14.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ pypi_name[0] }}/{{ pypi_name }}/typst-{{ version }}.tar.gz
  sha256: 8424387c4ea709caf0dcd54c44f736f86cdde421ac86f9a5d2fa76ba4978b50e

build:
  number: 0

requirements:
  build:
    - python                              # [build_platform != target_platform]
    - cross-python_{{ target_platform }}  # [build_platform != target_platform]
    - maturin                             # [build_platform != target_platform]
    - {{ compiler('c') }}
    - {{ stdlib("c") }}
    - {{ compiler('rust') }}
    - cargo-bundle-licenses
    - make
  host:
    - python
    - maturin >=1.0,<2.0
    - pip
  run:
    - python

test:
  imports:
    - typst
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/messense/typst-py
  summary: Python binding to typst
  license: Apache-2.0
  license_file:
    - LICENSE
    - THIRDPARTY.yml

extra:
  recipe-maintainers:
    - freundTech
    - pavelzw
